#!/usr/bin/env bash

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.

# Set keybaord input rate
xset r rate 200 55 &

# Set right control to mod3
xmodmap -e "clear control" -e "add control = Control_L" -e "clear mod3" -e "add mod3 = Control_R"

# Set right alt to mod5
xmodmap -e "clear mod1" -e "add mod1 = Alt_L" -e "clear mod5" -e "add mod5 = Alt_R"

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xrdbpid=$! # Xresources colors/settings on startup

# Set wallpaper
setbg $(readlink -f $HOME/.local/share/bg)

# Polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Place applications that are needed to autostarted
autostart="dwmblocks clipcatd mpd dunst picom nm-applet pulsedaemon unclutter"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Start emacs daemon
emacs --daemon &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
