#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.

# Set keybaord input rate
xset r rate 200 55 &

# Set wallpaper
setbg $(readlink -f $HOME/.local/share/bg)

# Polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Place applications that are needed to autostarted
autostart="slstatus mpd dunst picom nm-applet pulsedaemon"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1
