#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96	# Set DPI. User may want to use a larger number for larger screens.

xset r rate 200 40 & # Set keybaord input rate

setbg $(readlink -f $HOME/.local/share/bg) # set wallpaper


xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Xresources colors/settings on startup

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & 		# Polkit authentication agent


# For clipmenu
systemctl --user import-environment DISPLAY

# Place applications that are needed to autostarted
autostart="dwmblocks mpd dunst picom nm-applet pulsedaemon clipmenud"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
